[package]
name = "j2je"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
clap = { version = "4.5.48", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3